#!/usr/bin/env python3

SHEET_NAME = "H1B visa"
WORKSHEET_NAME = "Valid Entries"
DISCARDED_WORKSHEET = "Discarded Entries"
REVIEWED_WORKSHEET = "Reviewed - Not Applied"

SHEETS_CREDS_FILE = "credentials.json"
GMAIL_CREDS_FILE = "gmail_credentials.json"
GMAIL_TOKEN_FILE = "gmail_token.pickle"
JOBRIGHT_COOKIES_FILE = "jobright_cookies.json"

SIMPLIFY_URL = "https://raw.githubusercontent.com/SimplifyJobs/Summer2026-Internships/master/README.md"
VANSHB03_URL = (
    "https://raw.githubusercontent.com/vanshb03/Summer2026-Internships/main/README.md"
)

MAX_JOB_AGE_DAYS = 5
MIN_QUALITY_SCORE = 3

PLATFORM_DETECTION_PATTERNS = {
    "workday": r"\.wd\d+\.myworkdayjobs\.com",
    "greenhouse": r"(boards\.|job-boards\.)?greenhouse\.io",
    "lever": r"jobs\.lever\.co",
    "ashby": r"jobs\.ashbyhq\.com",
    "linkedin": r"linkedin\.com/jobs",
    "icims": r"\.icims\.com",
    "tiktok": r"(lifeattiktok|tiktok)\.com",
    "bytedance": r"(joinbytedance|bytedance)",
    "oracle": r"oraclecloud\.com",
    "eightfold": r"eightfold\.ai",
}

URL_TO_COMPANY_MAPPING = {
    r"quickenloans\.wd\d+\.myworkdayjobs\.com": "Rocket Companies",
    r"geico\.wd\d+\.myworkdayjobs\.com": "GEICO",
    r"redhat\.wd\d+\.myworkdayjobs\.com": "Red Hat",
    r"cinemark\.wd\d+\.myworkdayjobs\.com": "Cinemark",
    r"astrazeneca\.wd\d+\.myworkdayjobs\.com": "AstraZeneca",
    r"sherwin\.wd\d+\.myworkdayjobs\.com": "Sherwin-Williams",
    r"manulife\.wd\d+\.myworkdayjobs\.com": "Manulife",
    r"wellsky\.wd\d+\.myworkdayjobs\.com": "WellSky",
    r"micron\.wd\d+\.myworkdayjobs\.com": "Micron Technology",
    r"cox\.wd\d+\.myworkdayjobs\.com": "Cox Automotive",
    r"adobe\.wd\d+\.myworkdayjobs\.com": "Adobe",
    r"roche\.wd\d+\.myworkdayjobs\.com": "Roche",
    r"cartech\.wd\d+\.myworkdayjobs\.com": "Carpenter Technology",
    r"cranecompany\.wd\d+\.myworkdayjobs\.com": "Crane Aerospace",
    r"motorola.*\.wd\d+\.myworkdayjobs\.com": "Motorola Solutions",
    r"careers-lmi\.icims\.com": "LMI",
    r"careers-kinaxis\.icims\.com": "Kinaxis",
    r"university-uber\.icims\.com": "Uber",
    r"aexp\.eightfold\.ai": "American Express",
    r"ejhp\.fa\.us\d+\.oraclecloud\.com": "Sherwin-Williams",
    r"jobs\.ashbyhq\.com/[Cc]rusoe": "Crusoe Energy",
    r"(lifeattiktok|careers\.tiktok)\.com": "TikTok",
    r"(joinbytedance|careers\.bytedance)": "ByteDance",
}

COMPANY_SLUG_MAPPING = {
    "google": "Google",
    "microsoft": "Microsoft",
    "apple": "Apple",
    "amazon": "Amazon",
    "meta": "Meta",
    "facebook": "Meta",
    "netflix": "Netflix",
    "tesla": "Tesla",
    "tiktok": "TikTok",
    "bytedance": "ByteDance",
    "linkedin": "LinkedIn",
    "twitter": "Twitter",
    "snapchat": "Snapchat",
    "pinterest": "Pinterest",
    "reddit": "Reddit",
    "openai": "OpenAI",
    "anthropic": "Anthropic",
    "togetherai": "Together AI",
    "together-ai": "Together AI",
    "huggingface": "Hugging Face",
    "hugging-face": "Hugging Face",
    "scaleai": "Scale AI",
    "scale-ai": "Scale AI",
    "perplexity": "Perplexity",
    "cohere": "Cohere",
    "stripe": "Stripe",
    "square": "Square",
    "plaid": "Plaid",
    "ramp": "Ramp",
    "brex": "Brex",
    "affirm": "Affirm",
    "chime": "Chime",
    "robinhood": "Robinhood",
    "notion": "Notion",
    "figma": "Figma",
    "airtable": "Airtable",
    "asana": "Asana",
    "monday": "Monday.com",
    "slack": "Slack",
    "zoom": "Zoom",
    "dropbox": "Dropbox",
    "databricks": "Databricks",
    "snowflake": "Snowflake",
    "cloudflare": "Cloudflare",
    "datadog": "Datadog",
    "splunk": "Splunk",
    "rivian": "Rivian",
    "cruise": "Cruise",
    "waymo": "Waymo",
    "zoox": "Zoox",
    "uber": "Uber",
    "lyft": "Lyft",
    "doordash": "DoorDash",
    "instacart": "Instacart",
    "shopify": "Shopify",
    "ebay": "eBay",
    "etsy": "Etsy",
    "roblox": "Roblox",
    "unity": "Unity",
    "epicgames": "Epic Games",
    "jpmorgan": "JPMorgan Chase",
    "goldmansachs": "Goldman Sachs",
    "morganstanley": "Morgan Stanley",
    "bankofamerica": "Bank of America",
    "wellsfargo": "Wells Fargo",
    "capitalone": "Capital One",
    "americanexpress": "American Express",
    "citigroup": "Citigroup",
    "motorolasolutions": "Motorola Solutions",
    "pelco": "Motorola Solutions",
    "boeing": "Boeing",
    "lockheedmartin": "Lockheed Martin",
    "northropgrumman": "Northrop Grumman",
    "raytheon": "Raytheon Technologies",
    "att": "AT&T",
    "verizon": "Verizon",
    "tmobile": "T-Mobile",
    "salesforce": "Salesforce",
    "oracle": "Oracle",
    "sap": "SAP",
    "servicenow": "ServiceNow",
    "workday": "Workday",
    "nvidia": "NVIDIA",
    "intel": "Intel",
    "amd": "AMD",
    "qualcomm": "Qualcomm",
    "crusoe": "Crusoe Energy",
    "nuro": "Nuro",
    "nimblerx": "NimbleRx",
    "singlestore": "SingleStore",
    "geico": "GEICO",
}

COMPANY_NAME_PREFIXES = [
    "lifeat",
    "joinat",
    "join",
    "careersat",
    "careers",
    "workfor",
    "workat",
    "work",
    "hiringat",
    "hiring",
]

COMPANY_NAME_STOPWORDS = [
    "Careers at ",
    "Careers | ",
    "Work at ",
    "Join ",
    " Careers",
    " Jobs",
    " - Careers",
    " Career Site",
    " | Careers",
    " | Jobs",
    " - Jobs",
]

COMPANY_PLACEHOLDERS = [
    "Unknown",
    "N/A",
    "Company",
    "Employer",
    "Organization",
    "Adzuna",
    "Jobright",
    "ZipRecruiter",
    "Careers",
    "Jobs",
    "External",
    "Portal",
    "Applicant",
    "Apply",
]

SPECIAL_COMPANY_NAMES = {
    "sig": "Susquehanna International Group",
    "nuro": "Nuro",
    "nimblerx": "NimbleRx",
    "singlestore": "SingleStore",
    "geico": "GEICO",
    "aexp": "American Express",
    "amex": "American Express",
}

ROLE_CATEGORIES = {
    "Pure Software": {
        "keywords": [
            "backend",
            "frontend",
            "full stack",
            "fullstack",
            "web developer",
            "mobile developer",
            "application developer",
            "software development",
            "web engineer",
            "mobile engineer",
            "app developer",
        ],
        "exclude": ["embedded", "firmware", "hardware", "fpga", "asic"],
        "action": "ACCEPT",
        "alert": "✅ SOFTWARE",
    },
    "Data & AI": {
        "keywords": [
            "data scien",
            "machine learning",
            "ml engineer",
            "ai engineer",
            "data engineer",
            "analytics",
            "data analyst",
            "business intelligence",
            "deep learning",
            "computer vision",
            "nlp",
            "ai research",
        ],
        "exclude": [],
        "action": "ACCEPT",
        "alert": "✅ DATA/AI",
    },
    "DevOps & Infrastructure": {
        "keywords": [
            "devops",
            "sre",
            "site reliability",
            "cloud engineer",
            "infrastructure",
            "platform engineer",
        ],
        "exclude": ["embedded systems", "hardware"],
        "action": "ACCEPT",
        "alert": "✅ DEVOPS",
    },
    "Embedded & Firmware": {
        "keywords": [
            "embedded",
            "firmware",
            "iot",
            "robotics",
            "real-time systems",
            "microcontroller",
            "embedded linux",
            "rtos",
        ],
        "exclude": [],
        "action": "FLAG",
        "alert": "⚠️  EMBEDDED/FIRMWARE",
    },
    "Hardware Engineering": {
        "keywords": [
            "hardware engineer",
            "fpga",
            "asic",
            "vlsi",
            "pcb design",
            "circuit design",
            "digital design",
            "analog",
        ],
        "exclude": ["software"],
        "action": "FLAG_STRICT",
        "alert": "⚠️⚠️  HARDWARE",
    },
    "Security & QA": {
        "keywords": [
            "security engineer",
            "cybersecurity",
            "qa engineer",
            "test automation",
            "quality assurance",
        ],
        "exclude": [],
        "action": "ACCEPT",
        "alert": "✅ SECURITY/QA",
    },
}

USER_ROLE_PREFERENCES = {
    "auto_accept": [
        "Pure Software",
        "Data & AI",
        "DevOps & Infrastructure",
        "Security & QA",
    ],
    "flag_for_review": ["Embedded & Firmware"],
    "flag_strict": ["Hardware Engineering"],
}

WORKDAY_HQ_CODES = {
    "USNYNYC": ("New York", "NY"),
    "USCASFO": ("San Francisco", "CA"),
    "USWAEAT": ("Seattle", "WA"),
    "USTXAUS": ("Austin", "TX"),
    "USMABOA": ("Boston", "MA"),
}

LOCATION_CODE_PATTERNS = [
    r"^US([A-Z]{2})([A-Z]{3})$",
    r"^US-([A-Z]{2})-",
]

STATUS_COLORS = {
    "Not Applied": {"red": 1.0, "green": 1.0, "blue": 1.0},
    "Applied": {"red": 1.0, "green": 0.9, "blue": 0.6},
    "OA Sent": {"red": 0.7, "green": 0.85, "blue": 1.0},
    "OA Completed": {"red": 0.4, "green": 0.7, "blue": 1.0},
    "Interview Scheduled": {"red": 1.0, "green": 0.8, "blue": 0.4},
    "Interviewed": {"red": 1.0, "green": 0.65, "blue": 0.3},
    "Offer Received": {"red": 0.6, "green": 0.9, "blue": 0.6},
    "Offer accepted": {"red": 0.2, "green": 0.7, "blue": 0.2},
    "Rejected": {"red": 1.0, "green": 0.6, "blue": 0.6},
    "Ghosted": {"red": 0.8, "green": 0.8, "blue": 0.8},
}

GMAIL_SCOPES = ["https://www.googleapis.com/auth/gmail.readonly"]

USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
]

US_STATES = {
    "alabama": "AL",
    "alaska": "AK",
    "arizona": "AZ",
    "arkansas": "AR",
    "california": "CA",
    "colorado": "CO",
    "connecticut": "CT",
    "delaware": "DE",
    "florida": "FL",
    "georgia": "GA",
    "hawaii": "HI",
    "idaho": "ID",
    "illinois": "IL",
    "indiana": "IN",
    "iowa": "IA",
    "kansas": "KS",
    "kentucky": "KY",
    "louisiana": "LA",
    "maine": "ME",
    "maryland": "MD",
    "massachusetts": "MA",
    "michigan": "MI",
    "minnesota": "MN",
    "mississippi": "MS",
    "missouri": "MO",
    "montana": "MT",
    "nebraska": "NE",
    "nevada": "NV",
    "new hampshire": "NH",
    "new jersey": "NJ",
    "new mexico": "NM",
    "new york": "NY",
    "north carolina": "NC",
    "north dakota": "ND",
    "ohio": "OH",
    "oklahoma": "OK",
    "oregon": "OR",
    "pennsylvania": "PA",
    "rhode island": "RI",
    "south carolina": "SC",
    "south dakota": "SD",
    "tennessee": "TN",
    "texas": "TX",
    "utah": "UT",
    "vermont": "VT",
    "virginia": "VA",
    "washington": "WA",
    "west virginia": "WV",
    "wisconsin": "WI",
    "wyoming": "WY",
    "district of columbia": "DC",
}

STATE_NAME_TO_CODE = US_STATES.copy()

CANADA_PROVINCES = {
    "ON",
    "QC",
    "BC",
    "AB",
    "MB",
    "SK",
    "NS",
    "NB",
    "NL",
    "PE",
    "YT",
    "NT",
    "NU",
}

CITY_TO_STATE = {
    "san francisco": "CA",
    "san jose": "CA",
    "palo alto": "CA",
    "mountain view": "CA",
    "sunnyvale": "CA",
    "santa clara": "CA",
    "cupertino": "CA",
    "menlo park": "CA",
    "redwood city": "CA",
    "foster city": "CA",
    "san mateo": "CA",
    "fremont": "CA",
    "san carlos": "CA",
    "los angeles": "CA",
    "san diego": "CA",
    "irvine": "CA",
    "santa monica": "CA",
    "pasadena": "CA",
    "berkeley": "CA",
    "oakland": "CA",
    "sacramento": "CA",
    "fresno": "CA",
    "long beach": "CA",
    "anaheim": "CA",
    "cerritos": "CA",
    "san bruno": "CA",
    "burbank": "CA",
    "santa barbara": "CA",
    "new york": "NY",
    "brooklyn": "NY",
    "manhattan": "NY",
    "queens": "NY",
    "bronx": "NY",
    "staten island": "NY",
    "albany": "NY",
    "buffalo": "NY",
    "rochester": "NY",
    "syracuse": "NY",
    "yonkers": "NY",
    "white plains": "NY",
    "seattle": "WA",
    "bellevue": "WA",
    "redmond": "WA",
    "tacoma": "WA",
    "spokane": "WA",
    "pullman": "WA",
    "olympia": "WA",
    "vancouver": "WA",
    "boston": "MA",
    "cambridge": "MA",
    "somerville": "MA",
    "worcester": "MA",
    "natick": "MA",
    "framingham": "MA",
    "quincy": "MA",
    "waltham": "MA",
    "newton": "MA",
    "brookline": "MA",
    "houston": "TX",
    "dallas": "TX",
    "austin": "TX",
    "san antonio": "TX",
    "fort worth": "TX",
    "el paso": "TX",
    "arlington": "TX",
    "plano": "TX",
    "irving": "TX",
    "richardson": "TX",
    "chicago": "IL",
    "naperville": "IL",
    "aurora": "IL",
    "rockford": "IL",
    "des plaines": "IL",
    "la grange park": "IL",
    "schaumburg": "IL",
    "north chicago": "IL",
    "phoenix": "AZ",
    "tucson": "AZ",
    "mesa": "AZ",
    "chandler": "AZ",
    "scottsdale": "AZ",
    "tempe": "AZ",
    "gilbert": "AZ",
    "philadelphia": "PA",
    "pittsburgh": "PA",
    "allentown": "PA",
    "reading": "PA",
    "denver": "CO",
    "colorado springs": "CO",
    "boulder": "CO",
    "aurora": "CO",
    "atlanta": "GA",
    "augusta": "GA",
    "columbus": "GA",
    "savannah": "GA",
    "alpharetta": "GA",
    "miami": "FL",
    "orlando": "FL",
    "tampa": "FL",
    "jacksonville": "FL",
    "fort lauderdale": "FL",
    "tallahassee": "FL",
    "st petersburg": "FL",
    "sarasota": "FL",
    "plantation": "FL",
    "detroit": "MI",
    "grand rapids": "MI",
    "warren": "MI",
    "ann arbor": "MI",
    "dearborn": "MI",
    "minneapolis": "MN",
    "st paul": "MN",
    "rochester": "MN",
    "bloomington": "MN",
    "shakopee": "MN",
    "chaska": "MN",
    "portland": "OR",
    "salem": "OR",
    "eugene": "OR",
    "hillsboro": "OR",
    "beaverton": "OR",
    "las vegas": "NV",
    "reno": "NV",
    "henderson": "NV",
    "baltimore": "MD",
    "frederick": "MD",
    "rockville": "MD",
    "gaithersburg": "MD",
    "germantown": "MD",
    "annapolis": "MD",
    "silver spring": "MD",
    "hanover": "MD",
    "north bethesda": "MD",
    "chevy chase": "MD",
    "westbrook": "ME",
    "portland": "ME",
    "lewiston": "ME",
    "milwaukee": "WI",
    "madison": "WI",
    "green bay": "WI",
    "nashville": "TN",
    "memphis": "TN",
    "knoxville": "TN",
    "indianapolis": "IN",
    "fort wayne": "IN",
    "evansville": "IN",
    "columbus": "OH",
    "cleveland": "OH",
    "cincinnati": "OH",
    "toledo": "OH",
    "brecksville": "OH",
    "charlotte": "NC",
    "raleigh": "NC",
    "cary": "NC",
    "durham": "NC",
    "greensboro": "NC",
    "chapel hill": "NC",
    "wilmington": "NC",
    "salt lake city": "UT",
    "provo": "UT",
    "west valley city": "UT",
    "oklahoma city": "OK",
    "tulsa": "OK",
    "norman": "OK",
    "louisville": "KY",
    "lexington": "KY",
    "kansas city": "MO",
    "st louis": "MO",
    "springfield": "MO",
    "omaha": "NE",
    "lincoln": "NE",
    "albuquerque": "NM",
    "santa fe": "NM",
    "boise": "ID",
    "meridian": "ID",
    "des moines": "IA",
    "cedar rapids": "IA",
    "little rock": "AR",
    "fayetteville": "AR",
    "providence": "RI",
    "warwick": "RI",
    "bridgeport": "CT",
    "new haven": "CT",
    "stamford": "CT",
    "hartford": "CT",
    "newark": "NJ",
    "jersey city": "NJ",
    "princeton": "NJ",
    "hoboken": "NJ",
    "richmond": "VA",
    "virginia beach": "VA",
    "norfolk": "VA",
    "chesapeake": "VA",
    "arlington": "VA",
    "alexandria": "VA",
    "mclean": "VA",
    "reston": "VA",
    "charleston": "SC",
    "columbia": "SC",
    "greenville": "SC",
    "birmingham": "AL",
    "montgomery": "AL",
    "huntsville": "AL",
    "new orleans": "LA",
    "baton rouge": "LA",
    "shreveport": "LA",
    "jackson": "MS",
    "gulfport": "MS",
    "honolulu": "HI",
    "pearl city": "HI",
    "anchorage": "AK",
    "fairbanks": "AK",
    "manchester": "NH",
    "nashua": "NH",
    "concord": "NH",
    "burlington": "VT",
    "essex": "VT",
    "sioux falls": "SD",
    "rapid city": "SD",
    "fargo": "ND",
    "bismarck": "ND",
    "billings": "MT",
    "missoula": "MT",
    "bozeman": "MT",
    "helena": "MT",
    "cheyenne": "WY",
    "casper": "WY",
    "wilmington": "DE",
    "dover": "DE",
    "overland park": "KS",
    "lynnwood": "WA",
}

CANADA_CITIES = {
    "toronto": "ON",
    "markham": "ON",
    "ottawa": "ON",
    "mississauga": "ON",
    "montreal": "QC",
    "quebec city": "QC",
    "quebec": "QC",
    "vancouver": "BC",
    "victoria": "BC",
    "burnaby": "BC",
    "calgary": "AB",
    "edmonton": "AB",
    "winnipeg": "MB",
    "regina": "SK",
    "halifax": "NS",
}

JOB_BOARD_DOMAINS = [
    "greenhouse",
    "lever.co",
    "workday",
    "ashbyhq",
    "smartrecruiters",
    "icims.com",
    "myworkdayjobs",
    "jobs.lever.co",
    "boards.greenhouse.io",
    "job-boards.greenhouse.io",
    "simplify.jobs",
    "linkedin.com/jobs",
    "indeed.com",
    "glassdoor.com",
    "angellist.com",
    "wellfound.com",
    "monster.com",
    "dice.com",
    "builtin.com",
    "ycombinator.com/jobs",
    "stackoverflow.com/jobs",
    "jobs.github.com",
    "careers.",
    "apply.workable.com",
    "breezy.hr",
    "recruiting.",
    "talentify",
    "workable",
    "jobvite",
    "ultipro",
    "paylocity",
    "paycomonline",
    "bamboohr",
    "fountain.com",
    "ziprecruiter",
    "ziprecruiter.com",
    "adzuna",
    "adzuna.com",
    "jobright",
    "jobright.ai",
    "fursah",
    "fursah.com",
]
