#!/usr/bin/env python3
"""
Configuration module for job aggregation pipeline.
Production v3.0: Complete company mappings, Handshake fixes
"""

# Sheet Configuration
SHEET_NAME = "H1B visa"
WORKSHEET_NAME = "Valid Entries"
DISCARDED_WORKSHEET = "Discarded Entries"
REVIEWED_WORKSHEET = "Reviewed - Not Applied"

# Credentials
SHEETS_CREDS_FILE = "credentials.json"
GMAIL_CREDS_FILE = "gmail_credentials.json"
GMAIL_TOKEN_FILE = "gmail_token.pickle"
JOBRIGHT_COOKIES_FILE = "jobright_cookies.json"

# External Sources
SIMPLIFY_URL = "https://raw.githubusercontent.com/SimplifyJobs/Summer2026-Internships/master/README.md"
VANSHB03_URL = (
    "https://raw.githubusercontent.com/vanshb03/Summer2026-Internships/main/README.md"
)
GMAIL_SCOPES = ["https://www.googleapis.com/auth/gmail.readonly"]

# User Agents for rotation
USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
]

# US States mapping
US_STATES = {
    "alabama": "AL",
    "alaska": "AK",
    "arizona": "AZ",
    "arkansas": "AR",
    "california": "CA",
    "colorado": "CO",
    "connecticut": "CT",
    "delaware": "DE",
    "florida": "FL",
    "georgia": "GA",
    "hawaii": "HI",
    "idaho": "ID",
    "illinois": "IL",
    "indiana": "IN",
    "iowa": "IA",
    "kansas": "KS",
    "kentucky": "KY",
    "louisiana": "LA",
    "maine": "ME",
    "maryland": "MD",
    "massachusetts": "MA",
    "michigan": "MI",
    "minnesota": "MN",
    "mississippi": "MS",
    "missouri": "MO",
    "montana": "MT",
    "nebraska": "NE",
    "nevada": "NV",
    "new hampshire": "NH",
    "new jersey": "NJ",
    "new mexico": "NM",
    "new york": "NY",
    "north carolina": "NC",
    "north dakota": "ND",
    "ohio": "OH",
    "oklahoma": "OK",
    "oregon": "OR",
    "pennsylvania": "PA",
    "rhode island": "RI",
    "south carolina": "SC",
    "south dakota": "SD",
    "tennessee": "TN",
    "texas": "TX",
    "utah": "UT",
    "vermont": "VT",
    "virginia": "VA",
    "washington": "WA",
    "west virginia": "WV",
    "wisconsin": "WI",
    "wyoming": "WY",
    "district of columbia": "DC",
}

# Canadian Provinces
CANADA_PROVINCES = {
    "ON",
    "QC",
    "BC",
    "AB",
    "MB",
    "SK",
    "NS",
    "NB",
    "NL",
    "PE",
    "YT",
    "NT",
    "NU",
}

# City to State mapping (for faster lookup)
CITY_TO_STATE = {
    "new york": "NY",
    "brooklyn": "NY",
    "manhattan": "NY",
    "queens": "NY",
    "bronx": "NY",
    "los angeles": "CA",
    "san francisco": "CA",
    "san diego": "CA",
    "san jose": "CA",
    "palo alto": "CA",
    "mountain view": "CA",
    "sunnyvale": "CA",
    "santa clara": "CA",
    "cupertino": "CA",
    "menlo park": "CA",
    "redwood city": "CA",
    "irvine": "CA",
    "santa monica": "CA",
    "pasadena": "CA",
    "berkeley": "CA",
    "oakland": "CA",
    "sacramento": "CA",
    "fresno": "CA",
    "long beach": "CA",
    "anaheim": "CA",
    "cerritos": "CA",
    "san mateo": "CA",
    "fremont": "CA",
    "san carlos": "CA",
    "hanover": "MD",
    "des plaines": "IL",
    "la grange park": "IL",
    "west valley city": "UT",
    "salt lake city": "UT",
    "provo": "UT",
    "seattle": "WA",
    "bellevue": "WA",
    "redmond": "WA",
    "tacoma": "WA",
    "spokane": "WA",
    "boston": "MA",
    "cambridge": "MA",
    "somerville": "MA",
    "worcester": "MA",
    "natick": "MA",
    "chicago": "IL",
    "naperville": "IL",
    "aurora": "IL",
    "rockford": "IL",
    "houston": "TX",
    "dallas": "TX",
    "austin": "TX",
    "san antonio": "TX",
    "fort worth": "TX",
    "el paso": "TX",
    "arlington": "TX",
    "plano": "TX",
    "phoenix": "AZ",
    "tucson": "AZ",
    "mesa": "AZ",
    "chandler": "AZ",
    "scottsdale": "AZ",
    "philadelphia": "PA",
    "pittsburgh": "PA",
    "allentown": "PA",
    "denver": "CO",
    "colorado springs": "CO",
    "boulder": "CO",
    "atlanta": "GA",
    "augusta": "GA",
    "columbus": "GA",
    "savannah": "GA",
    "miami": "FL",
    "orlando": "FL",
    "tampa": "FL",
    "jacksonville": "FL",
    "fort lauderdale": "FL",
    "tallahassee": "FL",
    "st petersburg": "FL",
    "detroit": "MI",
    "grand rapids": "MI",
    "warren": "MI",
    "ann arbor": "MI",
    "minneapolis": "MN",
    "st paul": "MN",
    "rochester": "MN",
    "bloomington": "MN",
    "shakopee": "MN",
    "portland": "OR",
    "salem": "OR",
    "eugene": "OR",
    "hillsboro": "OR",
    "las vegas": "NV",
    "reno": "NV",
    "henderson": "NV",
    "baltimore": "MD",
    "frederick": "MD",
    "rockville": "MD",
    "gaithersburg": "MD",
    "germantown": "MD",
    "annapolis": "MD",
    "silver spring": "MD",
    "westbrook": "ME",
    "milwaukee": "WI",
    "madison": "WI",
    "green bay": "WI",
    "nashville": "TN",
    "memphis": "TN",
    "knoxville": "TN",
    "indianapolis": "IN",
    "fort wayne": "IN",
    "evansville": "IN",
    "columbus": "OH",
    "cleveland": "OH",
    "cincinnati": "OH",
    "toledo": "OH",
    "charlotte": "NC",
    "raleigh": "NC",
    "cary": "NC",
    "durham": "NC",
    "greensboro": "NC",
    "chapel hill": "NC",
    "wilmington": "NC",
    "oklahoma city": "OK",
    "tulsa": "OK",
    "norman": "OK",
    "louisville": "KY",
    "lexington": "KY",
    "kansas city": "MO",
    "st louis": "MO",
    "springfield": "MO",
    "omaha": "NE",
    "lincoln": "NE",
    "albuquerque": "NM",
    "santa fe": "NM",
    "boise": "ID",
    "meridian": "ID",
    "des moines": "IA",
    "cedar rapids": "IA",
    "little rock": "AR",
    "fayetteville": "AR",
    "providence": "RI",
    "warwick": "RI",
    "bridgeport": "CT",
    "new haven": "CT",
    "stamford": "CT",
    "hartford": "CT",
    "newark": "NJ",
    "jersey city": "NJ",
    "princeton": "NJ",
    "hoboken": "NJ",
    "richmond": "VA",
    "virginia beach": "VA",
    "norfolk": "VA",
    "chesapeake": "VA",
    "arlington": "VA",
    "alexandria": "VA",
    "mclean": "VA",
    "reston": "VA",
    "charleston": "SC",
    "columbia": "SC",
    "greenville": "SC",
    "birmingham": "AL",
    "montgomery": "AL",
    "huntsville": "AL",
    "new orleans": "LA",
    "baton rouge": "LA",
    "shreveport": "LA",
    "jackson": "MS",
    "gulfport": "MS",
    "honolulu": "HI",
    "pearl city": "HI",
    "anchorage": "AK",
    "fairbanks": "AK",
    "portland": "ME",
    "lewiston": "ME",
    "manchester": "NH",
    "nashua": "NH",
    "concord": "NH",
    "burlington": "VT",
    "essex": "VT",
    "sioux falls": "SD",
    "rapid city": "SD",
    "fargo": "ND",
    "bismarck": "ND",
    "billings": "MT",
    "missoula": "MT",
    "bozeman": "MT",
    "helena": "MT",
    "cheyenne": "WY",
    "casper": "WY",
    "newark": "DE",
    "wilmington": "DE",
    "dover": "DE",
    "chaska": "MN",
    "irving": "TX",
    "sarasota": "FL",
}

# Canadian Cities mapping
CANADA_CITIES = {
    "toronto": "ON",
    "markham": "ON",
    "ottawa": "ON",
    "mississauga": "ON",
    "montreal": "QC",
    "quebec city": "QC",
    "quebec": "QC",
    "vancouver": "BC",
    "victoria": "BC",
    "burnaby": "BC",
    "calgary": "AB",
    "edmonton": "AB",
    "winnipeg": "MB",
    "regina": "SK",
    "halifax": "NS",
}

# Job Board Domains
JOB_BOARD_DOMAINS = [
    "greenhouse",
    "lever.co",
    "workday",
    "ashbyhq",
    "smartrecruiters",
    "icims.com",
    "myworkdayjobs",
    "jobs.lever.co",
    "boards.greenhouse.io",
    "simplify.jobs",
    "linkedin.com/jobs",
    "indeed.com",
    "glassdoor.com",
    "angellist.com",
    "wellfound.com",
    "monster.com",
    "dice.com",
    "builtin.com",
    "ycombinator.com/jobs",
    "stackoverflow.com/jobs",
    "jobs.github.com",
    "careers.",
    "apply.workable.com",
    "breezy.hr",
    "recruiting.",
    "talentify",
    "workable",
    "jobvite",
    "ultipro",
    "paylocity",
    "paycomonline",
    "bamboohr",
    "fountain.com",
    "ziprecruiter",
    "ziprecruiter.com",
    "adzuna",
    "adzuna.com",
    "jobright",
    "jobright.ai",
    "fursah",
    "fursah.com",
]

# Company Name Mappings (PRODUCTION v3.0)
SPECIAL_COMPANY_NAMES = {
    "stanfordhealthcare": "Stanford Health Care",
    "bmo": "BMO",
    "jpmorgan": "JPMorgan",
    "figma": "Figma",
    "ibm": "IBM",
    "simplify": "Simplify Jobs",
    # Email/aggregator mappings
    "lifeattiktok": "TikTok",
    "githubinc": "GitHub",
    "ucar": "UCAR",
    "ncar": "NCAR",
    "seagatecareers": "Seagate",
    "adzuna": "Multiple Companies",
    "easyapply": "SAP SuccessFactors",
    # Company name fixes
    "joinbytedance": "ByteDance",
    "bytedance": "ByteDance",
    "mathworks": "MathWorks",
    "idexx": "IDEXX",
    "careersidexx": "IDEXX",
    "sig": "Susquehanna International Group",
    "careers": "Susquehanna International Group",
    "linkedin": "Ninth Wave",  # LinkedIn jobs come from Jobright email with real company
    "lever": "Lever",
    "ninthwave": "Ninth Wave",
    "ninth": "Ninth Wave",
    "nimblerx": "NimbleRx",
    "nimble": "NimbleRx",
    "nuro": "Nuro",
    "abb": "ABB",
    "oracle": "Oracle",
    "singlestore": "SingleStore",
    "myworkdayjobs": "Workday",
}

# Quality Scoring Thresholds
MIN_QUALITY_SCORE = 3
MAX_JOB_AGE_DAYS = 5

# Sheet Colors
STATUS_COLORS = {
    "Not Applied": {"red": 0.6, "green": 0.76, "blue": 1.0},
    "Applied": {"red": 0.58, "green": 0.93, "blue": 0.31},
    "Rejected": {"red": 0.97, "green": 0.42, "blue": 0.42},
    "OA Round 1": {"red": 1.0, "green": 0.95, "blue": 0.4},
    "OA Round 2": {"red": 1.0, "green": 0.95, "blue": 0.4},
    "Interview 1": {"red": 0.82, "green": 0.93, "blue": 0.94},
    "Offer accepted": {"red": 0.16, "green": 0.65, "blue": 0.27},
    "Assessment": {"red": 0.89, "green": 0.89, "blue": 0.89},
}

HANDSHAKE_COOKIES_FILE = "handshake_cookies.json"

# ✅ FIXED: Handshake configuration
HANDSHAKE_CONFIG = {
    "search_url": "https://app.joinhandshake.com/job-search/10591618?employmentTypes=1&employmentTypes=2&jobType=3&pay%5BsalaryType%5D=1&pay%5BpayMinimum%5D=2000&pay%5BpaySchedule%5D=HOURLY_WAGE&remoteWork=onsite&remoteWork=remote&remoteWork=hybrid&majors=135801&workAuthorization=openToUSVisaSponsorship&workAuthorization=openToOptionalPracticalTraining&workAuthorization=openToCurricularPracticalTraining&workAuthorization=noUSWork&per_page=25&page=1",  # ← YOU MUST UPDATE THIS!
    "max_jobs_per_session": 50,
    "max_sessions_per_day": 1,
    "scrape_only_weekdays": False,  # ✅ FIXED: Was True, now False (allow weekends)
    "scrape_hours": (8, 20),
    "delay_between_jobs": (5, 15),
    "scroll_delay": (1, 3),
    "read_time_per_job": (45, 90),
    "blank_click_probability": 0.3,
    "scroll_probability": 0.7,
    "extract_full_description": True,
    "extract_work_authorization": True,
    "extract_deadline": True,
    "posted_within_hours": 24,
    "stop_on_captcha": True,
    "retry_on_failure": False,
    "fail_silently": True,
}
